# Generated by Django 4.1.2 on 2023-01-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalequipos',
            table='inventario_equipos_historial',
        ),
    ]
