# Generated by Django 4.1.2 on 2023-01-16 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentosEmpresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresasId', to='it.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(default='S/N')),
                ('asignacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asignacionEq', to='it.asignaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='So',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TiposEquipos',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TiposRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('cargo', models.CharField(max_length=45)),
                ('departamentosEmpresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentoEmpresaUs', to='it.departamentosempresas')),
            ],
        ),
        migrations.CreateModel(
            name='TiposEquiposMarcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcas', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='marcasId', to='it.marcas')),
                ('tiposEquipos', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='tiposEquiposId', to='it.tiposequipos')),
            ],
        ),
        migrations.AddField(
            model_name='tiposequipos',
            name='marcas',
            field=models.ManyToManyField(related_name='tiposEquiposMarcas', through='it.TiposEquiposMarcas', to='it.marcas'),
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('tiposEquiposMarcas', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='tiposEquiposMarcasId', to='it.tiposequipos')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEquipos',
            fields=[
                ('nombre', models.CharField(max_length=45, null=True)),
                ('serial', models.CharField(blank=True, default='S/N', max_length=45)),
                ('serial_unidad', models.CharField(blank=True, default='S/N', max_length=45)),
                ('serial_cargador', models.CharField(blank=True, default='S/N', max_length=45)),
                ('csb', models.CharField(blank=True, default='S/N', max_length=45)),
                ('dd', models.CharField(blank=True, default='S/N', max_length=45)),
                ('ram', models.CharField(blank=True, default='S/N', max_length=45)),
                ('antivirus', models.CharField(blank=True, default='S/N', max_length=45)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresas', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.empresas')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.estado')),
                ('modelo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.modelos')),
                ('so', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.so')),
                ('tipo_ram', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.tiposram')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.usuarios')),
            ],
            options={
                'verbose_name': 'historical equipos',
                'verbose_name_plural': 'historical equiposs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='estado',
            name='estatu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estatusEq', to='it.estatus'),
        ),
        migrations.AddField(
            model_name='estado',
            name='ubicaciones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacionEq', to='it.ubicaciones'),
        ),
        migrations.AddField(
            model_name='departamentosempresas',
            name='empresas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentosId', to='it.empresas'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='empresas',
            field=models.ManyToManyField(related_name='empresasDepartamentos', through='it.DepartamentosEmpresas', to='it.empresas'),
        ),
        migrations.CreateModel(
            name='Impresoras',
            fields=[
                ('id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estado_imp', serialize=False, to='it.estado')),
                ('serial', models.CharField(default='S/N', max_length=45)),
                ('csb', models.CharField(default='S/N', max_length=45)),
                ('toner', models.CharField(max_length=45)),
                ('tipo_conexion', models.CharField(choices=[('NO APLICA', 'No aplica'), ('RED', 'Red'), ('USB', 'Usb'), ('COMPARTIDA', 'Compartida')], default='No aplica', max_length=45)),
                ('ip', models.CharField(default='No aplica', max_length=45)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentosImpresora', to='it.departamentos')),
                ('modelos', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='modelosImp', to='it.modelos')),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estadoEq', serialize=False, to='it.estado')),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('serial', models.CharField(blank=True, default='S/N', max_length=45)),
                ('serial_unidad', models.CharField(blank=True, default='S/N', max_length=45)),
                ('serial_cargador', models.CharField(blank=True, default='S/N', max_length=45)),
                ('csb', models.CharField(blank=True, default='S/N', max_length=45)),
                ('dd', models.CharField(blank=True, default='S/N', max_length=45)),
                ('ram', models.CharField(blank=True, default='S/N', max_length=45)),
                ('antivirus', models.CharField(blank=True, default='S/N', max_length=45)),
                ('empresas', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresasEq', to='it.empresas')),
                ('modelo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='modeloEq', to='it.modelos')),
                ('so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soEq', to='it.so')),
                ('tipo_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipoRamEq', to='it.tiposram')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioEq', to='it.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(default='S/N', max_length=45)),
                ('csb', models.CharField(default='S/N', max_length=45)),
                ('modelos', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='modelosDis', to='it.modelos')),
                ('asignado', models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='equiposDis', to='it.equipos')),
            ],
        ),
    ]
