# Generated by Django 4.1.2 on 2022-10-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('cargo', models.CharField(max_length=45)),
                ('departamentosforeignkey', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='departamentos_empresas_us', to='it.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='ubicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('empresasforeingkey', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='empresas_ub', to='it.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('marcasforeignkey', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='marcas_m', to='it.marcas')),
            ],
        ),
        migrations.CreateModel(
            name='informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=45)),
                ('asignacion', models.CharField(max_length=45)),
                ('observacion', models.TextField()),
                ('ubicacionesforeignkey', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_user', to='it.ubicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='impresoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=45)),
                ('serial', models.CharField(max_length=45)),
                ('csb', models.CharField(max_length=45)),
                ('cbc', models.CharField(max_length=45)),
                ('tipo_impresion', models.CharField(max_length=45)),
                ('tipo_conexion', models.CharField(max_length=45)),
                ('ip', models.CharField(max_length=45)),
                ('propiedad', models.CharField(max_length=45)),
                ('informacionforeignkey', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='informacion_im', to='it.informacion')),
                ('modelosforeignkey', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='modelos_imp', to='it.modelos')),
            ],
        ),
        migrations.CreateModel(
            name='dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=45)),
                ('informacionforeignkey', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='informacion_dis', to='it.informacion')),
                ('modelosforeignkey', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='modelos_dis', to='it.modelos')),
                ('usuariosforeignkey', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_us', to='it.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='departamentos',
            name='empresasforeignkey',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='empresas_de', to='it.empresas'),
        ),
        migrations.CreateModel(
            name='equipos',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='informacion_eq', serialize=False, to='it.informacion')),
                ('tipo_equipo', models.CharField(max_length=45)),
                ('serial', models.CharField(max_length=45)),
                ('serial_unidad', models.CharField(max_length=45)),
                ('serial_cargador', models.CharField(max_length=45)),
                ('csb', models.CharField(max_length=45)),
                ('dd', models.CharField(max_length=45)),
                ('ram', models.CharField(max_length=45)),
                ('tipo_ram', models.CharField(max_length=45)),
                ('antivirus', models.CharField(max_length=45)),
                ('so', models.CharField(max_length=45)),
                ('usuario_so', models.CharField(max_length=45)),
                ('modelosforeignkey', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='modelos_eq', to='it.modelos')),
                ('usuariosforeignkey', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='equipos_us', to='it.usuarios')),
            ],
        ),
    ]
