# Generated by Django 4.1.2 on 2023-01-11 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='asignaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='departamentos_empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresasId', to='it.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='so',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipos_equipos',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tiposRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ubicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('cargo', models.CharField(max_length=45)),
                ('departamentosEmpresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentoEmpresaUs', to='it.departamentos_empresas')),
            ],
        ),
        migrations.CreateModel(
            name='tipos_equipos_marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcas', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='marcasId', to='it.marcas')),
                ('tiposEquipos', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='tiposEquiposId', to='it.tipos_equipos')),
            ],
        ),
        migrations.AddField(
            model_name='tipos_equipos',
            name='marcas',
            field=models.ManyToManyField(related_name='tiposEquiposMarcas', through='it.tipos_equipos_marcas', to='it.marcas'),
        ),
        migrations.CreateModel(
            name='modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('tiposEquiposMarcas', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='tiposEquiposMarcasId', to='it.tipos_equipos_marcas')),
            ],
        ),
        migrations.CreateModel(
            name='informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(default='OPERATIVA', max_length=45)),
                ('asignacion', models.CharField(default='POR ASIGNAR', max_length=45)),
                ('observacion', models.TextField(default='S/N')),
                ('ubicaciones', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacionesUser', to='it.ubicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalequipos',
            fields=[
                ('serial', models.CharField(blank=True, default='S/N', max_length=45)),
                ('serial_unidad', models.CharField(blank=True, default='S/N', max_length=45)),
                ('serial_cargador', models.CharField(blank=True, default='S/N', max_length=45)),
                ('csb', models.CharField(blank=True, default='S/N', max_length=45)),
                ('dd', models.CharField(blank=True, default='S/N', max_length=45)),
                ('ram', models.CharField(blank=True, default='S/N', max_length=45)),
                ('tipo_ram', models.CharField(blank=True, default='S/N', max_length=45)),
                ('antivirus', models.CharField(blank=True, default='S/N', max_length=45)),
                ('so', models.CharField(blank=True, default='S/N', max_length=45)),
                ('usuario_so', models.CharField(max_length=45, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresas', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.empresas')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.informacion')),
                ('modelos', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.modelos')),
                ('usuarios', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.usuarios')),
            ],
            options={
                'verbose_name': 'historical equipos',
                'verbose_name_plural': 'historical equiposs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='departamentos_empresas',
            name='empresas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentosId', to='it.empresas'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='empresas',
            field=models.ManyToManyField(related_name='empresasDepartamentos', through='it.departamentos_empresas', to='it.empresas'),
        ),
        migrations.CreateModel(
            name='impresoras',
            fields=[
                ('id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='informacion_imp', serialize=False, to='it.informacion')),
                ('serial', models.CharField(default='S/N', max_length=45)),
                ('csb', models.CharField(default='S/N', max_length=45)),
                ('toner', models.CharField(max_length=45)),
                ('tipo_conexion', models.CharField(choices=[('NO APLICA', 'No aplica'), ('RED', 'Red'), ('USB', 'Usb'), ('COMPARTIDA', 'Compartida')], default='No aplica', max_length=45)),
                ('ip', models.CharField(default='No aplica', max_length=45)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentosImpresora', to='it.departamentos')),
                ('modelos', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='modelosImp', to='it.modelos')),
            ],
        ),
        migrations.CreateModel(
            name='equipos',
            fields=[
                ('id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='informacion_eq', serialize=False, to='it.informacion')),
                ('serial', models.CharField(blank=True, default='S/N', max_length=45)),
                ('serial_unidad', models.CharField(blank=True, default='S/N', max_length=45)),
                ('serial_cargador', models.CharField(blank=True, default='S/N', max_length=45)),
                ('csb', models.CharField(blank=True, default='S/N', max_length=45)),
                ('dd', models.CharField(blank=True, default='S/N', max_length=45)),
                ('ram', models.CharField(blank=True, default='S/N', max_length=45)),
                ('tipo_ram', models.CharField(blank=True, default='S/N', max_length=45)),
                ('antivirus', models.CharField(blank=True, default='S/N', max_length=45)),
                ('so', models.CharField(blank=True, default='S/N', max_length=45)),
                ('usuario_so', models.CharField(max_length=45, null=True)),
                ('empresas', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresasEq', to='it.empresas')),
                ('modelos', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelosEq', to='it.modelos')),
                ('usuarios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equiposUs', to='it.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(default='S/N', max_length=45)),
                ('csb', models.CharField(default='S/N', max_length=45)),
                ('modelos', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='modelosDis', to='it.modelos')),
                ('asignado', models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='equiposDis', to='it.equipos')),
            ],
        ),
    ]
