# Generated by Django 4.1.2 on 2022-10-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelos',
            name='marcasforeignkeyName',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='marcas_mName', to='it.marcas'),
            preserve_default='True',
        ),
    ]
