# Generated by Django 4.1.2 on 2022-11-11 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('it', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='tipo_equipo',
        ),
        migrations.CreateModel(
            name='Historicalequipos',
            fields=[
                ('serial', models.CharField(default='S/N', max_length=45)),
                ('serial_unidad', models.CharField(default='S/N', max_length=45)),
                ('serial_cargador', models.CharField(default='S/N', max_length=45)),
                ('csb', models.CharField(default='S/N', max_length=45)),
                ('dd', models.CharField(default='S/N', max_length=45)),
                ('ram', models.CharField(default='S/N', max_length=45)),
                ('tipo_ram', models.CharField(default='S/N', max_length=45)),
                ('antivirus', models.CharField(default='S/N', max_length=45)),
                ('so', models.CharField(default='S/N', max_length=45)),
                ('usuario_so', models.CharField(default='S/N', max_length=45)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresas', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.empresas')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.informacion')),
                ('modelos', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.modelos')),
                ('usuarios', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='it.usuarios')),
            ],
            options={
                'verbose_name': 'historical equipos',
                'verbose_name_plural': 'historical equiposs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
