# Generated by Django 4.1.2 on 2023-01-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departamentosempresas',
            table='it_departamentos_empresas',
        ),
        migrations.AlterModelTable(
            name='tiposequipos',
            table='it_tipos_equipos',
        ),
        migrations.AlterModelTable(
            name='tiposequiposmarcas',
            table='it_tipos_equipos_marcas',
        ),
    ]
