# Generated by Django 4.1.2 on 2022-10-20 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='modelosforeignkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_eq', to='it.modelos'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='ubicacionesforeignkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_user', to='it.ubicaciones'),
        ),
    ]
