# Generated by Django 4.1.2 on 2022-10-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos_equipos',
            name='marcas',
            field=models.ManyToManyField(related_name='tipos_equipos_marcas', through='it.tipos_equipos_marcas', to='it.marcas'),
        ),
    ]
