# Generated by Django 4.1.2 on 2022-11-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impresoras',
            old_name='tipoImpresion',
            new_name='toner',
        ),
    ]
