# Generated by Django 4.1.2 on 2022-10-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0002_alter_equipos_modelosforeignkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='usuariosforeignkey',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='equipos_us', to='it.usuarios'),
        ),
    ]
