# Generated by Django 4.1.2 on 2022-11-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0002_rename_tipoimpresion_impresoras_toner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresoras',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentoEmpresaImp', to='it.departamentos_empresas'),
        ),
    ]
