# Generated by Django 4.1.2 on 2022-11-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0002_remove_impresoras_tipo_impresion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipos_equipos',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
