# Generated by Django 4.1.2 on 2022-12-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0003_alter_tipos_equipos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='usuario_so',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalequipos',
            name='usuario_so',
            field=models.CharField(db_index=True, max_length=45, null=True),
        ),
    ]
