# Generated by Django 4.1.2 on 2022-11-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0003_alter_impresoras_propiedad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impresoras',
            old_name='propiedad',
            new_name='departamento',
        ),
    ]
