# Generated by Django 4.1.2 on 2022-11-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0004_rename_propiedad_impresoras_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impresoras',
            name='informacion',
        ),
        migrations.AlterField(
            model_name='impresoras',
            name='id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='informacion_imp', serialize=False, to='it.informacion'),
        ),
    ]
