# Generated by Django 4.1.2 on 2022-11-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0006_remove_impresoras_codigo_inventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresoras',
            name='tipo_impresion',
            field=models.CharField(choices=[('CINTA', 'Cinta'), ('TONER', 'Toner'), ('RIBON', 'Ribon'), ('TINTA', 'Tinta'), ('NO APLICA', 'No aplica')], max_length=45),
        ),
    ]
