# Generated by Django 4.1.2 on 2022-11-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0008_remove_impresoras_cbc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresoras',
            name='tipo_conexion',
            field=models.CharField(choices=[('RED', 'Red'), ('USB', 'Usb'), ('COMPARTIDA', 'Compartida')], max_length=45),
        ),
    ]
