# Generated by Django 4.1.2 on 2022-11-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0010_alter_impresoras_tipo_conexion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresoras',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentoEmpresaImp', to='it.departamentos'),
        ),
        migrations.AlterField(
            model_name='impresoras',
            name='tipo_conexion',
            field=models.CharField(choices=[('RED', 'Red'), ('USB', 'Usb'), ('COMPARTIDA', 'Compartida'), ('NO APLICA', 'No aplica')], default='No aplica', max_length=45),
        ),
    ]
