# Generated by Django 4.1.2 on 2022-11-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0011_alter_impresoras_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresoras',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentosImpresora', to='it.departamentos'),
        ),
    ]
