# Generated by Django 4.1.2 on 2022-11-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0012_alter_impresoras_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresoras',
            name='tipo_conexion',
            field=models.CharField(choices=[('NO APLICA', 'No aplica'), ('RED', 'Red'), ('USB', 'Usb'), ('COMPARTIDA', 'Compartida')], default='No aplica', max_length=45),
        ),
        migrations.AlterField(
            model_name='impresoras',
            name='tipo_impresion',
            field=models.CharField(choices=[('NO APLICA', 'No aplica'), ('CINTA', 'Cinta'), ('TONER', 'Toner'), ('RIBON', 'Ribon'), ('TINTA', 'Tinta')], max_length=45),
        ),
    ]
