# Generated by Django 4.1.2 on 2022-11-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0013_alter_impresoras_tipo_conexion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivos',
            name='informacion',
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='informacion_dis', serialize=False, to='it.informacion'),
        ),
    ]
