# Generated by Django 4.1.2 on 2022-11-25 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0014_remove_dispositivos_informacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivos',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='asignado',
            field=models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='equiposDis', to='it.equipos', to_field='usuario_so'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='csb',
            field=models.CharField(default='S/N', max_length=45),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='serial',
            field=models.CharField(default='S/N', max_length=45),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='usuario_so',
            field=models.CharField(blank=True, default='S/N', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalequipos',
            name='usuario_so',
            field=models.CharField(blank=True, db_index=True, default='S/N', max_length=45),
        ),
    ]
